// Demonstrates defining, throwing, catching, and handling exceptions.
#include <iostream>

int main()
{
    std::cout << "Exceptions!" << std::endl;
}